### ISSUE TITLE
@ tags are line-break sensitive

### ISSUE THREAD

**Issue by mtbuzato** [mundorum/oid#9]
If you define a template like this:

```html
<button
  type="button"
  @click>
    Hello!
</button>
```

It works fine, however, if you do it like this (which is how most formatters, like Prettier, work):

```html
<button
  type="button"
  @click
>
    Hello!
</button>
```

Notice where the closing tag `>` is being put. This causes the framework to break unexpectedly.

Stacktrace:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'bind')
    at ApplicationOid._buildEventDispatchers (oid-base.js:97:53)
    at ApplicationOid.render (oid-ui.js:27:14)
    at ApplicationOid.connectedCallback (oid-ui.js:13:10)
    at Oid.component (oid.js:99:20)
```

This is mostly due to how the Regex expression that looks for the @ tags work.

**Comment by mtbuzato** [comment]
The issue lives, most likely, here:
https://github.com/mundorum/oid/blob/5fc3483ea9856ed1592cae9cc6256d53fa16c159/src/base/oid.js#L103

**Comment by mtbuzato** [comment]
The way the template is split, means new line characters are being used to find their specific function dispatchers, which obviously don't exist.

![image](https://github.com/mundorum/oid/assets/42821095/a146b25f-767e-4817-99a7-63a80a3d38ee)

**Comment by mtbuzato** [comment]
A possible fix would be trimming the names before looking for their implementations:

```js
let funcName;

if (te[i + 2] == null) {
  funcName = te[i + 2];
} else {
  const tag = te[i + 1].trim();
  funcName = tag.charAt(0).toUpperCase() + tag.substring(1);
}
```

Replacing https://github.com/mundorum/oid/blob/5fc3483ea9856ed1592cae9cc6256d53fa16c159/src/base/oid.js#LL110C1-L112C24
